const presets = [
    {
        x_func: "-x^2 - t^2 + x*t - y*t - x",
        y_func: "-x^2 + t^2 + x*t - x - y",
        x_scale: 200, 
        y_scale: 200,
        x_offset: -30,
        y_offset: -75,
        point_size: 1,
        t_initial: -1,
        t_final: 0.7,
        t_rate: 0.0007,
        num_points: 500,
        trail_length: 5,
        color_scheme: 0,
        connect_trail: "false"
    },
    {
        x_func: "x^2 - x*t + y*t - x",
        y_func: "-y^2 - t^2 - x*y - x*t - y*t - y",
        x_scale: 400,
        y_scale: 400,
        x_offset: 200,
        y_offset: -150,
        point_size: 1,
        t_initial: 0.15,
        t_final: 0.56,
        t_rate: 0.0002,
        num_points: 1000,
        trail_length: 5,
        color_scheme: 5,
        connect_trail: "false"
    },
    {
        x_func: "-x^2 + y^2 + t^2 - x*y + y*t - t",
        y_func: "y^2 - x + t",
        x_scale: 450,
        y_scale: 450,
        x_offset: 0,
        y_offset: 0,
        point_size: 1,
        t_initial: -0.16,
        t_final: -0.11,
        t_rate: 0.00002,
        num_points: 400,
        trail_length: 10,
        color_scheme: 0,
        connect_trail: "false"
    },
    {
        x_func: "x^2 + y^2 - x*y + y*t - t",
        y_func: "y^2 - x + t",
        x_scale: 450,
        y_scale: 450,
        x_offset: 50,
        y_offset: 100,
        point_size: 1,
        t_initial: 0,
        t_final: 0.48,
        t_rate: 0.0002,
        num_points: 500,
        trail_length: 8,
        color_scheme: 0,
        connect_trail: "false"
    }, 
    {
        x_func: "x^2 + t^2 + y^2 - x*t - x + y",
        y_func: "x^2 + x*t + y + t",
        x_scale: 350,
        y_scale: 350,
        x_offset: 0,
        y_offset: -250,
        point_size: 1,
        t_initial: -0.4,
        t_final: 0.1,
        t_rate: 0.0003,
        num_points: 500,
        trail_length: 5,
        color_scheme: 0,
        connect_trail: "false"
    },
    {
        x_func: "y*t + t^2 - y - y^2 + x*t - t^2",
        y_func: "x^2 - x + y - t",
        x_scale: 300,
        y_scale: 300,
        x_offset: 0,
        y_offset: 0,
        point_size: 1,
        t_initial: -0.1,
        t_final: 0.23,
        t_rate: 0.0002,
        num_points: 600,
        trail_length: 9,
        color_scheme: 6,
        connect_trail: "false"
    },
    {
        x_func: "y*t + t^2 - y - y^2 + x*t - t^2",
        y_func: "x^2 - x + y - t",
        x_scale: 300,
        y_scale: 300,
        x_offset: 0,
        y_offset: 0,
        point_size: 1,
        t_initial: -0.1,
        t_final: 0.23,
        t_rate: 0.0002,
        num_points: 600,
        trail_length: 9,
        color_scheme: 6,
        connect_trail: "false"
    },
    {
        x_func: "-t^2 - y^2 - x*y - x*t - y*t - x - t",
        y_func: "t^2 - x*t -y",
        x_scale: 400,
        y_scale: 400,
        x_offset: 0,
        y_offset: 0,
        point_size: 1,
        t_initial: -0.3,
        t_final: 0.3,
        t_rate: 0.0005,
        num_points: 800,
        trail_length: 10,
        color_scheme: 0,
        connect_trail: "false"
    },
    {
        x_func: "x^2 + y^2 - x*y + y*t - x - t",
        y_func: "-t^2 - y^2 - x*y - x*t + y + t",
        x_scale: 600,
        y_scale: 600,
        x_offset: 50,
        y_offset: 50,
        point_size: 3,
        t_initial: -0.02,
        t_final: 0.8,
        t_rate: 0.0005,
        num_points: 500,
        trail_length: 10,
        color_scheme: 2,
        connect_trail: "false"
    },
    {
        x_func: "x*y*t - x^2 - y - t^2",
        y_func: "x*y*t + x + y^2 + t",
        x_scale: 600,
        y_scale: 600,
        x_offset: -100,
        y_offset: -70,
        point_size: 1,
        t_initial: -0.8,
        t_final: 0.35,
        t_rate: 0.0004,
        num_points: 500,
        trail_length: 10,
        color_scheme: 0,
        connect_trail: "true"
    },
    {
        x_func: "t^2 + x*y + x^2 - 2y^2 - x*t + y",
        y_func: "x^2 + y - t^2 + x*y",
        x_scale: 500,
        y_scale: 500,
        x_offset: 0,
        y_offset: 0,
        point_size: 1,
        t_initial: -0.55,
        t_final: 0.7,
        t_rate: 0.0006,
        num_points: 600,
        trail_length: 15,
        color_scheme: 0,
        connect_trail: "false"
    },
    {
        x_func: "2(x*y) - x*t + x - t - t^2 + x^2 - x*t",
        y_func: "- x^2 - t^2 - x*y + y - y*t + 2t",
        x_scale: 400,
        y_scale: 400,
        x_offset: -350,
        y_offset: 150,
        point_size: 1,
        t_initial: 0.6,
        t_final: 1.02,
        t_rate: 0.0001,
        num_points: 700,
        trail_length: 7,
        color_scheme: 0,
        connect_trail: "false"
    },
    {
        x_func: "x^2 - x + y - t - x*t + y^2",
        y_func: "-x*y - x^2 + 2x*t + t + x - t^2",
        x_scale: 500,
        y_scale: 500,
        x_offset: 250,
        y_offset: 0,
        point_size: 2,
        t_initial: -0.1,
        t_final: 0.3,
        t_rate: 0.0002,
        num_points: 500,
        trail_length: 5,
        color_scheme: 10,
        connect_trail: "false"
    },
    {
        x_func: "x*t + y^2 - y*t + x^2",
        y_func: "y*t - t^2",
        x_scale: 600,
        y_scale: 600,
        x_offset: 0,
        y_offset: -300,
        point_size: 1,
        t_initial: -1.02,
        t_final: -0.76,
        t_rate: 0.0001,
        num_points: 500,
        trail_length: 5,
        color_scheme: 9,
        connect_trail: "true"
    },
    {
        x_func: "y^2 - x*y + y*t - t",
        y_func: "y^2 - x + t^2",
        x_scale: 450,
        y_scale: 450,
        x_offset: 150,
        y_offset: -25,
        point_size: 2,
        t_initial: -0.23,
        t_final: -0.13,
        t_rate: 0.00003,
        num_points: 400,
        trail_length: 10,
        color_scheme: 0,
        connect_trail: "false"
    },
    {
        x_func: "y^2 - x*y + y*t - t",
        y_func: "y^2 - x + t^2",
        x_scale: 1500,
        y_scale: 1500,
        x_offset: 0,
        y_offset: 800,
        point_size: 1,
        t_initial: 0.40,
        t_final: 0.61,
        t_rate: 0.0001,
        num_points: 500,
        trail_length: 15,
        color_scheme: 11,
        connect_trail: "true"
    },
    {
        x_func: "-y + t^2 + x^2",
        y_func: "2x^2 + y*t",
        x_scale: 400,
        y_scale: 400,
        x_offset: 100,
        y_offset: 50,
        point_size: 1,
        t_initial: -0.68,
        t_final: -0.665,
        t_rate: 0.000006,
        num_points: 500,
        trail_length: 15,
        color_scheme: 0,
        connect_trail: "false"
    },
    {
        x_func: "y*t + t^2 - t + x + y + x^2",
        y_func: "x^2 + 2x*y - t - x",
        x_scale: 400,
        y_scale: 400,
        x_offset: 0,
        y_offset: 0,
        point_size: 1,
        t_initial: -0.1,
        t_final: 0.08,
        t_rate: 0.00005,
        num_points: 1000,
        trail_length: 8,
        color_scheme: 0,
        connect_trail: "false"
    },
]

window.presets = presets;
